soar-configs:
    execuable_path: ${soar}
    user: root
    password: 123456
    host: 127.0.0.1
    port: 3306
    database: blog
    skills:
      -report-type:
        type: 1
        default: true
      -allow-online-as-test:
        type : 1
        default: true
      -profiling:
        type : 1
        default: true
      -verbose:
        type : 1
        default: true
spring:
    aop:
      proxy-target-class: true
      auto: true
    thymeleaf:
      prefix: classpath:/templates/
      check-template: true
      mode: HTML5
